import { useState, useEffect } from 'react';
import { Loader, Form } from '../components';
import RenderPost from '../components/RenderPost';

const Home = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [posts, setPosts] = useState(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {}, []);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          Image Feed
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
          Browse Collection of other images generated by DALL-E AI System
        </p>
      </div>
      <div className="mt-16">
        <Form />
      </div>
      <div className="mt-10">
        {isLoading && (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        )}
        {searchText && (
          <h2 className="font-medium text-[#666e75] text-xl mb-3">
            Search Results for:{' '}
            <span className="text-[#222328]">{searchText}</span>
          </h2>
        )}
        <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
          {searchText ? (
            <RenderPost data={[]} title="No Results Found" />
          ) : (
            <RenderPost data={[]} title="No Posts Found" />
          )}
        </div>
      </div>
    </section>
  );
};

export default Home;
